spring:
  server:
    servlet:
      context-path: /main
  datasource:
    url: jdbc:postgresql://localhost:5432/TicketOrdery
    username: postgres
    password: 1234567890
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  h2:
    console:
      enabled: true
  flyway:
    enabled: true
    user: postgres
    password: 1234567890
    url: jdbc:postgresql://localhost:5432/TicketOrdery
    cleanDisabled: false
    baseline-on-migrate: true
