CREATE TABLE IF NOT EXISTS Ticket (
id BIGSERIAL PRIMARY KEY,
cost NUMERIC(10, 2) NOT NULL,
number INT NOT NULL,
customer_id BIGINT,
event_id BIGINT NOT NULL,
status BOOLEAN DEFAULT FALSE NOT NULL,
CONSTRAINT fk_ticket_customer FOREIGN KEY (customer_id) REFERENCES Customer(id) ON DELETE CASCADE,
CONSTRAINT fk_ticket_event FOREIGN KEY (event_id) REFERENCES Event(id) ON DELETE CASCADE
);